### ISSUE TITLE
Cannot be installed under luarocks/lua 5.4

### ISSUE THREAD

**Issue by oktoberfest6** [xHasKx/luamqtt#37]
Hi,

luamqtt does not install under luarocks for lua 5.4.
the culprit appears to be the line "lua >= 5.1, < 5.4" in the rockspec file.
Changing the '5.4' to '5.5' allows building/installation of luamqtt under lua 5.4/luarocks.

**Comment by xHasKx** [comment]
Hi @oktoberfest6 ,

I've fixed and updated rockspec file on the luarocks.

That Lua version limitation was because the copas project also does not define it: https://github.com/keplerproject/copas/blob/master/rockspec/copas-3.0.0-1.rockspec#L30
(@Tieske can you please take a look?)

The luamqtt does not depend on copas directly but can be used as one of the available connectors and it's used in tests: https://github.com/xHasKx/luamqtt/blob/master/tests/spec/mqtt-client.lua#L515

Now I just changed the tests runner script to avoid testing copas for the Lua 5.4 in the commit 7c62daa

**Comment by Tieske** [comment]
Just uploaded a new rockspec for Copas, Lua 5.4 is now supported
